# Generated by Django 6.0 on 2025-12-21 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('edge', models.IntegerField(default=0)),
                ('heart', models.IntegerField(default=0)),
                ('iron', models.IntegerField(default=0)),
                ('shadow', models.IntegerField(default=0)),
                ('wits', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('spirit', models.IntegerField(default=0)),
                ('supply', models.IntegerField(default=0)),
                ('momentum', models.IntegerField(default=0)),
                ('momentum_max', models.IntegerField(default=10)),
                ('momentum_reset', models.IntegerField(default=2)),
                ('experice', models.IntegerField(default=0)),
                ('bonds_progress', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.assetdefinition')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='characters.character')),
            ],
            options={
                'unique_together': {('character', 'asset_definition')},
            },
        ),
        migrations.CreateModel(
            name='Debility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('debility_type', models.CharField(choices=[('cond', 'Condition'), ('bane', 'Bane'), ('burd', 'Burden')], max_length=4)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debilites', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Vow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('progress', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[(1, 'troublesome'), (2, 'dangerous'), (3, 'formidable'), (4, 'extreme'), (5, 'epic')], max_length=20)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vows', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteAssetAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.assetabilitydefinition')),
                ('character_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='characters.characterasset')),
            ],
            options={
                'unique_together': {('character_asset', 'asset_ability')},
            },
        ),
    ]
