# Generated by Django 6.0 on 2025-12-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='character',
            name='momentum',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='character',
            name='spirit',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='character',
            name='supply',
            field=models.IntegerField(default=5),
        ),
    ]
