# Generated by Django 6.0 on 2025-12-22 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_health_alter_character_momentum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debility',
            name='debility_type',
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debility',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debilities', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='debility',
            name='name',
            field=models.CharField(choices=[('wounded', 'Condition: Wounded'), ('shaken', 'Condition: Shaken'), ('unprepared', 'Condition: Unprepared'), ('encumbered', 'Condition: Encumbered'), ('maimed', 'Bane: Maimed'), ('corrupted', 'Bane: Corrupted'), ('cursed', 'Burden: Cursed'), ('tormented', 'Burden: Tormented')], max_length=20),
        ),
    ]
