# Generated by Django 6.0 on 2025-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_debility_debility_type_alter_character_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vow',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'troublesome'), (2, 'dangerous'), (3, 'formidable'), (4, 'extreme'), (5, 'epic')], max_length=20),
        ),
    ]
