# Generated by Django 6.0 on 2025-12-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_vow_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vow',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'troublesome'), (2, 'dangerous'), (3, 'formidable'), (4, 'extreme'), (5, 'epic')]),
        ),
    ]
