# Generated by Django 6.0 on 2025-12-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_vow_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='experice',
            new_name='experience',
        ),
    ]
