# Generated by Django 6.0 on 2025-12-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_rename_experice_character_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteassetability',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
