# Generated by Django 6.0 on 2025-12-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_characteassetability_is_active'),
        ('rules', '0007_rename_name_customassetability_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacteAssetAbility',
            new_name='CharacterAssetAbility',
        ),
    ]
