# Generated by Django 6.0 on 2025-12-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_rename_characteassetability_characterassetability'),
        ('rules', '0007_rename_name_customassetability_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterassetability',
            name='custom_asset_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.customassetability'),
        ),
        migrations.AddField(
            model_name='characterassetability',
            name='custom_asset_ability_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
