# Generated by Django 6.0 on 2025-12-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_characterassetability_custom_asset_ability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterassetability',
            name='custom_asset_ability',
        ),
        migrations.RemoveField(
            model_name='characterassetability',
            name='custom_asset_ability_value',
        ),
    ]
