# Generated by Django 6.0 on 2025-12-25 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_remove_characterassetability_custom_asset_ability_and_more'),
        ('rules', '0009_rename_name_assetdefinition_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterasset',
            old_name='asset_definition',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='characterassetability',
            old_name='asset_ability',
            new_name='definition',
        ),
        migrations.AlterUniqueTogether(
            name='characterasset',
            unique_together={('character', 'definition')},
        ),
        migrations.AlterUniqueTogether(
            name='characterassetability',
            unique_together={('character_asset', 'definition')},
        ),
        migrations.CreateModel(
            name='CharacterAssetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('character_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='characters.characterasset')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.assetcomponentdefinition')),
            ],
            options={
                'unique_together': {('character_asset', 'definition')},
            },
        ),
    ]
