# Generated by Django 6.0 on 2025-12-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_rename_asset_definition_characterasset_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterassetcomponent',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
