# Generated by Django 6.0 on 2025-12-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_alter_characterassetcomponent_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='debility',
            name='type',
            field=models.CharField(choices=[('cond', 'Condition'), ('bane', 'Bane'), ('burd', 'Burden')], default='cond', max_length=4),
            preserve_default=False,
        ),
    ]
