# Generated by Django 6.0 on 2026-01-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_debility_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='bonds_progress',
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(verbose_name="Character's descrption and/or background"),
        ),
        migrations.AlterField(
            model_name='character',
            name='edge',
            field=models.IntegerField(default=0, verbose_name='Stat: Edge'),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0, help_text='Spendable on new assets or asset upgrades', verbose_name='Gained experience points'),
        ),
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=5, verbose_name='Tracker: Health'),
        ),
        migrations.AlterField(
            model_name='character',
            name='heart',
            field=models.IntegerField(default=0, verbose_name='Stat: Heart'),
        ),
        migrations.AlterField(
            model_name='character',
            name='iron',
            field=models.IntegerField(default=0, verbose_name='Stat: Iron'),
        ),
        migrations.AlterField(
            model_name='character',
            name='momentum',
            field=models.IntegerField(default=2, verbose_name='Tracker: Momentum'),
        ),
        migrations.AlterField(
            model_name='character',
            name='momentum_max',
            field=models.IntegerField(default=10, verbose_name='Maximal Momentum'),
        ),
        migrations.AlterField(
            model_name='character',
            name='momentum_reset',
            field=models.IntegerField(default=2, verbose_name='Momentum Reset value'),
        ),
        migrations.AlterField(
            model_name='character',
            name='shadow',
            field=models.IntegerField(default=0, verbose_name='Stat: Shadow'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spirit',
            field=models.IntegerField(default=5, verbose_name='Tracker: Spirit'),
        ),
        migrations.AlterField(
            model_name='character',
            name='supply',
            field=models.IntegerField(default=5, verbose_name='Tracker: Supply'),
        ),
        migrations.AlterField(
            model_name='character',
            name='wits',
            field=models.IntegerField(default=0, verbose_name='Stat: Wits'),
        ),
    ]
