# Generated by Django 6.0 on 2026-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_remove_character_bonds_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterassetability',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only active abilities provide narrative and mechanical effects', verbose_name='Is this ability active for this character'),
        ),
    ]
