# Generated by Django 6.0 on 2026-01-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_alter_characterassetability_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vow',
            name='progress',
            field=models.IntegerField(default=0, help_text='ticks, not progress boxes'),
        ),
        migrations.CreateModel(
            name='MinorQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('journey', 'Journey'), ('fight', 'Fight')], max_length=10)),
                ('difficulty', models.IntegerField(choices=[(1, 'troublesome'), (2, 'dangerous'), (3, 'formidable'), (4, 'extreme'), (5, 'epic')])),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, help_text='ticks, not progress boxes')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='characters.character')),
            ],
        ),
    ]
