# Generated by Django 6.0 on 2026-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_alter_vow_progress_minorquest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debility',
            options={'verbose_name_plural': 'Debilities'},
        ),
        migrations.AlterModelOptions(
            name='minorquest',
            options={'ordering': ['modified_at']},
        ),
        migrations.AddField(
            model_name='minorquest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='used to display last modifed quet on charsheet'),
        ),
    ]
