# Generated by Django 6.0 on 2026-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_alter_debility_options_alter_minorquest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vow',
            name='title',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
