# Generated by Django 6.0 on 2026-01-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_vow_title_alter_vow_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='momentum_max',
        ),
        migrations.RemoveField(
            model_name='character',
            name='momentum_reset',
        ),
    ]
