# Generated by Django 6.0 on 2026-01-23 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_remove_character_momentum_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spent_experience',
            field=models.IntegerField(default=0, verbose_name='Alredy spent experience points'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('spent_experience__lte', models.F('experience'))), name='spent_experience_lte_experience'),
        ),
    ]
