# Generated by Django 6.0 on 2026-01-23 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_character_spent_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('experience__lte', 30)), name='experience_lte_MAX_EXPERIENCE'),
        ),
    ]
