# Generated by Django 6.0 on 2026-01-23 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_character_experience_lte_max_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='experience_lte_MAX_EXPERIENCE',
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('experience__lte', 20)), name='experience_lte_MAX_EXPERIENCE'),
        ),
    ]
