# Generated by Django 6.0 on 2026-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_remove_character_experience_lte_max_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vow',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
