# Generated by Django 6.0 on 2026-01-12 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ironlands', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorldTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(choices=[('old world', 'The Old World'), ('iron', 'Iron'), ('legacies', 'Legacies'), ('communities', 'Communities'), ('leaders', 'Leaders'), ('defense', 'Defense'), ('religion', 'Religion'), ('mysticism', 'Mysticism'), ('firsborns', 'The Fisrtborns'), ('beasts', 'Beasts'), ('horrors', 'The Horrors')])),
                ('answer', models.TextField()),
                ('quest_starter', models.TextField(blank=True, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
        ),
    ]
