# Generated by Django 6.0 on 2026-01-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldtruth',
            name='question',
            field=models.TextField(choices=[('old_world', 'The Old World'), ('iron', 'Iron'), ('legacies', 'Legacies'), ('communities', 'Communities'), ('leaders', 'Leaders'), ('defense', 'Defense'), ('religion', 'Religion'), ('mysticism', 'Mysticism'), ('firsborns', 'The Fisrtborns'), ('beasts', 'Beasts'), ('horrors', 'The Horrors')]),
        ),
        migrations.AlterField(
            model_name='worldtruth',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truths', to='worlds.world'),
        ),
    ]
