# Generated by Django 6.0 on 2026-01-12 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0017_alter_debility_options_alter_minorquest_options_and_more'),
        ('rules', '0015_alter_move_options'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prologue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField()),
                ('character', models.ForeignKey(blank=True, help_text='Character primarily responsible for this event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character')),
                ('move', models.ForeignKey(blank=True, help_text='Move that was made during the event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.move')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gameplay.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='characters.character')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.story')),
            ],
            options={
                'unique_together': {('story', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='story',
            name='participants',
            field=models.ManyToManyField(through='gameplay.StoryParticipant', to='characters.character'),
        ),
    ]
