# Generated by Django 6.0 on 2026-01-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['story', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='order',
        ),
    ]
