# Generated by Django 6.0 on 2026-01-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_event_options_alter_story_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['world', 'title'], 'verbose_name_plural': 'Stories'},
        ),
    ]
