# Generated by Django 6.0 on 2025-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdefinition',
            name='type',
            field=models.CharField(choices=[('companion', 'Companion'), ('path', 'Path'), ('combat', 'Combat Talent'), ('ritual', 'Ritual')], default='test', max_length=20),
            preserve_default=False,
        ),
    ]
