# Generated by Django 6.0 on 2025-12-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_assetdefinition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetabilitydefinition',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
