# Generated by Django 6.0 on 2025-12-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_assetabilitydefinition_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetabilitydefinition',
            old_name='is_active',
            new_name='initially_active',
        ),
    ]
