# Generated by Django 6.0 on 2025-12-24 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_rename_is_active_assetabilitydefinition_initially_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAssetAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('tracker', models.IntegerField(blank=True, default=0, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_abilities', to='rules.assetdefinition')),
            ],
        ),
    ]
