# Generated by Django 6.0 on 2025-12-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_customassetabilities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomAssetAbilities',
            new_name='CustomAssetAbility',
        ),
    ]
