# Generated by Django 6.0 on 2025-12-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_rename_customassetabilities_customassetability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customassetability',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='customassetability',
            name='tracker',
        ),
        migrations.RemoveField(
            model_name='customassetability',
            name='value',
        ),
    ]
