# Generated by Django 6.0 on 2025-12-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_rename_name_customassetability_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetabilitydefinition',
            old_name='name',
            new_name='title',
        ),
    ]
