# Generated by Django 6.0 on 2025-12-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_rename_name_assetdefinition_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('adventure', 'Adventure'), ('relationship', 'Relationship'), ('combat', 'Combat'), ('suffer', 'Suffer'), ('quest', 'Quest'), ('fate', 'Fate')], max_length=20)),
                ('trigger_text', models.TextField()),
                ('outcome_text', models.TextField()),
                ('conditional_text', models.TextField(blank=True)),
                ('roll_type', models.CharField(choices=[('action', 'Action Roll'), ('progress', 'Progress Roll'), ('oracle', 'Oracle Roll'), ('none', 'No Roll')], max_length=20)),
            ],
        ),
    ]
