# Generated by Django 6.0 on 2025-12-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='name',
            new_name='title',
        ),
    ]
