# Generated by Django 6.0 on 2025-12-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_rename_name_move_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='full_text_temp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='conditional_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
