# Generated by Django 6.0 on 2025-12-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0012_move_full_text_temp_alter_move_conditional_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='conditional_text',
        ),
        migrations.RemoveField(
            model_name='move',
            name='full_text_temp',
        ),
    ]
