# Generated by Django 6.0 on 2026-01-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0013_remove_move_conditional_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetabilitydefinition',
            name='description',
            field=models.TextField(help_text='Narrative and mechanical features of the related `AssetDefinition` object if this ability is active'),
        ),
        migrations.AlterField(
            model_name='assetabilitydefinition',
            name='initially_active',
            field=models.BooleanField(default=False, help_text='Whether this ability is aleary active when picking up the asset'),
        ),
        migrations.AlterField(
            model_name='assetabilitydefinition',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ability name(if any)'),
        ),
        migrations.AlterField(
            model_name='assetcomponentdefinition',
            name='title',
            field=models.CharField(max_length=20, verbose_name="Compontent's name: e.g. name of the companion/god/patron"),
        ),
        migrations.AlterField(
            model_name='assetdefinition',
            name='description',
            field=models.TextField(help_text="Asset's narrative description. Some assets don't have description. Asset's `title` used in such case", verbose_name='Asset description'),
        ),
        migrations.AlterField(
            model_name='assetdefinition',
            name='title',
            field=models.CharField(help_text='Name of the asset as listed in the Ironsworn Asset Library(Master Set).', max_length=20, verbose_name='Asset name'),
        ),
        migrations.AlterField(
            model_name='assetdefinition',
            name='type',
            field=models.CharField(choices=[('companion', 'Companion'), ('path', 'Path'), ('combat', 'Combat Talent'), ('ritual', 'Ritual')], help_text='Classification of the asset. Purely narrative', max_length=20, verbose_name='Asset type'),
        ),
        migrations.AlterField(
            model_name='move',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('relationship', 'Relationship'), ('combat', 'Combat'), ('suffer', 'Suffer'), ('quest', 'Quest'), ('fate', 'Fate')], help_text='Category of the move. Purely narrative.', max_length=20, verbose_name='Move category'),
        ),
        migrations.AlterField(
            model_name='move',
            name='outcome_text',
            field=models.TextField(help_text='Usually the outcome of the move on strong/weak hit or miss. Sometimes narrative outcome', verbose_name='Move outcome'),
        ),
        migrations.AlterField(
            model_name='move',
            name='roll_type',
            field=models.CharField(choices=[('action', 'Action Roll'), ('progress', 'Progress Roll'), ('oracle', 'Oracle Roll'), ('none', 'No Roll')], help_text="Roll required to make the move. Some moves require oracle roll after action roll. The move's role type is `action` in such case", max_length=20),
        ),
        migrations.AlterField(
            model_name='move',
            name='title',
            field=models.CharField(help_text='Move name used in Ironsworn Rules Reference', max_length=50, unique=True, verbose_name='Move name'),
        ),
        migrations.AlterField(
            model_name='move',
            name='trigger_text',
            field=models.TextField(help_text='Narrative event that triggers the move. Also, mechanical conditions and actions need to make the move', verbose_name='Move trigger'),
        ),
    ]
