# Generated by Django 6.0 on 2026-01-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0014_alter_assetabilitydefinition_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['category', 'title']},
        ),
    ]
